import { Project } from "./types";

export const PROJECTS: Project[] = [
    {
        id: "bukit-baruga",
        title: "Bukit Baruga",
        link: "www.bukitbaruga.co.id",
        url: "https://www.bukitbaruga.co.id",
        category: "WEBSITE",
        image: "/projects/baruga.webp",
        bgColor: "#2d4e16",
        accentColor: "#39651c",
    },
    {
        id: "katakaltim",
        title: "Katakaltim",
        link: "katakaltim.com",
        url: "https://katakaltim.com",
        category: "NEWS",
        image: "/projects/katakaltim.webp",
        bgColor: "#0066f5",
        accentColor: "#1a75f8",
    },
    {
        id: "idnlab",
        title: "IDNLAB",
        link: "www.idnlab.com",
        url: "https://www.idnlab.com",
        category: "LABORATORY",
        image: "/projects/idnlab.webp",
        bgColor: "#0053cf",
        accentColor: "#0562e8",
    },
    {
        id: "aurora",
        title: "Aurora",
        link: "aurora-atelier.com",
        url: "https://aurora-atelier.com",
        category: "E-COMMERCE",
        image: "/projects/aurora.webp",
        bgColor: "#211f1d",
        accentColor: "#322e2a",
    },
    {
        id: "finvest",
        title: "Finvest",
        link: "finvest.io",
        url: "https://finvest.io",
        category: "FINTECH",
        image: "/projects/finvest.webp",
        bgColor: "#14122d",
        accentColor: "#211c47",
    },
];
